### PR TITLE
Add support for different registries configuration thru json

### PR DESCRIPTION
**Pull request by timansky**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | yes

### What's in this PR?
1. Add new env variables to override docker config (config.json), aws credentials (~/.aws/credentials)
and GCR
2. JSON_KEY variable for GCR deprecated

### CODE REVIEW

**Comment by bonifaido** [comment]
Hi @timansky, thanks for the PR! Where can I check these deprecations (sorry, I'm not aware of this), could you please provide me any docs links for that?

**Comment by timansky** [comment]
plugin avalible here: https://hub.docker.com/r/timansky/drone-kaniko-plugin

readme changed related to PR

Pushing to private docker hub:

```yaml
kind: pipeline
name: default

steps:
- name: publish
  image: banzaicloud/drone-kaniko
  settings:
    registry: gcr.io
    repo: example.com/example-project
    tags: ${DRONE_COMMIT_SHA}
    cache: true
    authjson_docker:
      from_secret: docker-config-json
```

Pushing to GCR:

```yaml
kind: pipeline
name: default

steps:
- name: publish
  image: banzaicloud/drone-kaniko
  settings:
    registry: gcr.io
    repo: example.com/example-project
    tags: ${DRONE_COMMIT_SHA}
    cache: true
    authjson_gcr:
      from_secret: google-application-credentials
```

Pushing to AWS:

```yaml
kind: pipeline
name: default

steps:
- name: publish
  image: banzaicloud/drone-kaniko
  settings:
    registry: gcr.io
    repo: example.com/example-project
    tags: ${DRONE_COMMIT_SHA}
    cache: true
    authjson_aws:
      from_secret: aws-credential-json
````
PS
old syntax  for gcr is still available

**Comment by jcardoso-bv** [comment]
Are there any plans to merge this PR? We require the new functionality to be able to push images to AWS ECR like so:

```
  - name: kaniko
    image: timansky/drone-kaniko-plugin
    settings:
      authjson_docker: '{"credsStore":"ecr-login"}'
      registry: 123456123456.dkr.ecr.eu-west-1.amazonaws.com
      repo: test/test
```

Existing plugin settings don't offer a way to override `/kaniko/.docker/config.json` with the required contents above to enable automated AWS ECR auth. This PR provides a suitable workaround.

**Comment by bonifaido** [comment]
Thanks, FYI: this project lives on in https://github.com/Riscue/drone-kaniko

**Pull request closed without merging**
